eps: 0.001
#eval_mode: False
eval_mode: True

# optimizer
lr: 0.0001
# train
data_dir: '/content/DiffMOT/danctrack/dancetrack/trackers_gt_t/'
diffnet: HMINet
interval: 9
augment: True
encoder_dim: 256
tf_layer: 3
epochs: 800
batch_size: 2048
seed: 123
eval_every: 20
gpus: [0,1,2,3]

# Testing
eval_at: 800
dataset: DanceTrack
det_dir: "/content/DiffMOT/danctrack/dancetrack/detections/test"
info_dir: '/content/DiffMOT/danctrack/dancetrack/test'
reid_dir: "/content/DiffMOT"
save_dir: "/content/DiffMOT/rerults"
eval_expname: mot_ddm_1000_deeper
high_thres: 0.6
low_thres: 0.4
w_assoc_emb: 2.2
aw_param: 1.7
preprocess_workers: 16

# Data Parameters:
device: cuda
eval_device: cuda
